apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-template-dashboard
  title: Python Flask com Dashboard Grafana
  description: Cria uma aplicação Flask com dashboard automatizado no Grafana
spec:
  owner: development
  type: service

  parameters:
    - title: Informações básicas
      required:
        - app_name
      properties:
        app_name:
          title: Nome da aplicação
          type: string
          description: Nome do seu serviço/app
        app_env:
          title: Ambiente
          type: string
          default: dev
          enum: [dev, staging, prod]

  steps:
    - id: fetch-base
      name: Buscar template base
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{ parameters.app_name }}
          app_env: ${{ parameters.app_env }}

    - id: criar-dashboard
      name: Criar dashboard no Grafana
      action: custom:create-grafana-dashboard
      input:
        dashboardName: ${{ parameters.app_name }}-dashboard
        folderName: ${{ parameters.app_env }}
        jsonTemplatePath: ./packages/backend/src/templates/grafana-base-dashboard.json

  output:
    links:
      - title: Acessar pasta do código
        url: https://github.com/sua-org/${{ parameters.app_name }}
      - title: Acessar dashboard no Grafana
        url: http://localhost:3333/d/${{ parameters.app_name }}-dashboard
